# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Updates pairwise global coverage matrix
#'
#' @param coverage full coverage matrix
#' @param subsample a vector that maps the subsample to the previous global sample
update_coverage_matrix <- function(coverage, subsample) {
    invisible(.Call('_SC3_update_coverage_matrix', PACKAGE = 'SC3', coverage, subsample))
}

#' Merges the subsample consensus matrix of to the global one 
#' to the original matrix
#' 
#' @param subsample_consensus the consensus matrix produced from the SC3 sub system
#' @param global_consensus the global consensus_matrix, no shared access
#' @param subsample_map the subsampling matrix
subsample_merge <- function(subsample_consensus, global_consensus, subsample_map) {
    invisible(.Call('_SC3_subsample_merge', PACKAGE = 'SC3', subsample_consensus, global_consensus, subsample_map))
}

#' Consensus matrix computation
#' 
#' Computes consensus matrix given cluster labels
#' 
#' @param dat a matrix containing clustering solutions in columns
#' @param K number of clusters
consmx <- function(dat, K) {
    .Call('_SC3_consmx', PACKAGE = 'SC3', dat, K)
}

#' Matrix left-multiplied by its transpose
#' 
#' Given matrix A, the procedure returns A'A.
#' 
#' @param x Numeric matrix.
tmult <- function(x) {
    .Call('_SC3_tmult', PACKAGE = 'SC3', x)
}

#' Converts the distance matrix to adjacency matrix
#' 
#' Given matrix A, the procedure returns a transformed matrix A'.
#' 
#' @param x Numeric matrix.
distance_to_adjacency_mat <- function(A) {
    .Call('_SC3_distance_to_adjacency_mat', PACKAGE = 'SC3', A)
}

